export default {
    "COOKIE": "COOKIE",
    "ATTENDANCE_DATA": "ATTENDANCE_DATA",
    "TEACHER_TIMETABLE": "TEACHER_TIMETABLE",
    "DIGITAL_DIRECTORY": "DIGITAL_DIRECTORY",
    "KIET_EXTENSION": "KIET_EXTENSION",
    "OFFLINE_ATTENDANCE": "OFFLINE_ATTENDANCE",
    "PROFILE_DATA": "PROFILE_DATA",
    "NEW_NOTIFICATION":"NEW_NOTIFICATION",
    "NOTIFICATION_DATA":"NOTIFICATION_DATA"
}